### ISSUE TITLE
Semiconductor band gap from resistivity data

### ISSUE THREAD

**Issue by vstewar4** [materialsautomated/materialsautomated.github.io#10]
Input: PPMS resistivity .dat file. A csv file containing a header and 41 columns of data (some empty), including temperature and resistivity (ρ) for up to three samples.

Output: A plot of ln(ρ) vs 1/T, with a linear fit to the appropriate data range and a band gap calculated from the slope.

Detailed description: The band gap of a semiconductor is related to the measured resistivity by 
![image](https://user-images.githubusercontent.com/63131020/78413095-e2201200-75e3-11ea-9d2e-be073c7d8ede.png)

It can be computed from the slope of a ln(ρ) vs 1/T plot. It would be useful to have a tool to read the PPMS data file, select the appropriate columns (temperature and resistivity or resistance), calculate and plot ln(ρ) and 1/T, perform a linear fit to the appropriate high-temperature range, and convert from slope to band gap.

Additional features could include identifying which of the three bridges where samples are measured contain useful data, and a way to input the sample dimensions for conversion between resistance and resistivity if they're not entered correctly in the data file.

Impact: This analysis of resistivity data is performed frequently for semiconducting materials. It can be done manually in Excel or Origin, but it would be helpful to speed the process up.

**Comment by tmcqueen-materials** [comment]
Thank you for this nice suggestion. Please include sample inputs and outputs; you can include arbitrary file types by putting them in a zip archive first.

**Comment by vstewar4** [comment]
Sample input data: BaFe2Se3, from [Caron et al., PhysRevB.85.180405](https://github.com/materialsautomated/materialsautomated.github.io/files/4475632/PhysRevB.85.180405.pdf)


[20111007_AFe2X3.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4471413/20111007_AFe2X3.zip) (BaFe2Se3, BaFe2S3, BaFe2S0.62Se2.38)
[20110928_AFe2X3.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4475946/20110928_AFe2X3.zip) (BaFe2S1.24Se1.76, Ba0.9K0.1Fe2Se3, Ba0.436K0.564Fe2Se3)
[20110927_AFe2X3.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4475947/20110927_AFe2X3.zip) (BaFe2S2.54Se0.46, Ba0.1K0.9Fe2Se3, Ba0.7K0.3Fe2Se3)
