### ISSUE TITLE
Utilizing DiffaX for fitting stacking faults

### ISSUE THREAD

**Issue by tanyaberry** [materialsautomated/materialsautomated.github.io#15]
Utilizing DiffaX for fitting stacking faults

Input: Raw files collected from Synchrotron source on layered MOF materials 

Output: To be able to tell the bonds length constant during layer stacking refinements input file as xy files, .data

Detailed Description: Solving the stacked structure of layered compounds using common software such as diffaX does the job to quite an extent. However, on refinement, it alters the bond lengths in the local structure to unphysical bonds while yielding to a good quantitative fit. Having a code set up to keep the bond distances as fixed variables (to enter in the diffax program) will allow us to compute the stacking faults rationally.

Impact: Such code shall be very useful in a solid-state chemistry lab for refinement purposes. It shall allow folks who are working on layered materials to keep local structures as a predefined unit. These units could then be used in software such as diffaX for arranging different stacking faults. 

Handling Data

Input: Raw files collected from Synchrotron source on layered MOF materials 

Example file for the tutorial (Kate+Tanya’s MOF data analysis):

Attached are the simple DiFFaX input files for the Ni and Cu MOFs. They are using the atom positions from the CIFs provided by the author/you (Ni: Cmcm; Cu C221), so watch those structural differences. The Ni structure has all the atoms fixed in the same xy plane, while the Cu structure has some up and down placement around its plane. *

The stacking of these, as written, is fixed in the eclipsed formation. (One could change this in the stacking section if needed stacked formation, random, xy sliding of the layers, and so on.)
 
The broadening for both is a 0.3 Gaussian to match best the Ni data. It's a maybe bit too broad for the Cu data, but it is a starting point. 

Additional info about the data:
SPXRD data from 11-BM@APS for Ni and CuHIB MOFs. Each of them collected under 100K and 295K using Calibrated wavelength = 0.517045 A.

[2016Nov16_2052.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4499376/2016Nov16_2052.zip)
[DiFFaX_input_files.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4499379/DiFFaX_input_files.zip)

**Comment by tmcqueen-materials** [comment]
Thank you very much for this excellent suggestion. Am I correct in understanding that you want something similar to (FAULTS)[https://onlinelibrary.wiley.com/doi/abs/10.1107/S1600576716014473], but with automatic generation of appropriate constraints on atomic positions with some given specifications? Is the idea that you would specify the "frozen" molecular units, that then only have translational and rotational degrees of freedom as a unit within the structure?

**Comment by tanyaberry** [comment]
Yes, exactly, thank you.

**Comment by tmcqueen-materials** [comment]
Here is a sample faulted x-ray diffraction data of Nb3Cl8. Has stacking faults 70% 2/3,1/3 translation, 30% 0,0 translation. And a shift of all Nb atoms by (+0.02,+0.02,-0.01). Refinement should recapture these values.
[Nb3Cl8-Faulted.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4547383/Nb3Cl8-Faulted.zip)
