### ISSUE TITLE
Heat capacity analysis

### ISSUE THREAD

**Issue by euclidmenot2** [materialsautomated/materialsautomated.github.io#5]
There seem to be some subtleties to the scipy.integrate.quad function that make this one more difficult than it looks.
 
This would involve importing the heat capacity data, plotting it, and fitting it to various combinations of Debye and Einstein models.

**Comment by tmcqueen-materials** [comment]
Thank you very much for the suggestion; could you provide perhaps some sample inputs and expected outputs, and perhaps a reference or two for the relevant integral equations?

**Comment by msinha1** [comment]
Input: PPMS .dat file containing heat capacity data of a sample. 
[input_hc analysis.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4431873/input_hc.analysis.zip)


Output: Cp/T3 vs Log T plot, Cp/T vs Log T fits showing the contributions from each of the phonon modes as well the total fit. A table with the temperature of each of the phonon modes as well as oscillator strengths. 
[output_hc analysis.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4431874/output_hc.analysis.zip)


Detailed description: We can approximate the 2D phonon DOS from the Cp/T3 vs T plot where Cp is the heat capacity of a material and T is the temperature. It will be useful to have a tool to identify and plot the graphs and fit the data showing the contribution of Einstein and Debye modes.

Additionally it will be really helpful if one set of parameters can be obtained by fitting the data in both the plots simultaneously.

Impact: It will reduce the time used for the analysis which is done manually. This fit is extremely useful for the structure and properties correlation of materials.
