### ISSUE TITLE
Quantum Espresso bands file processing

### ISSUE THREAD

**Issue by sbernie2** [materialsautomated/materialsautomated.github.io#6]
**Input:** QE .bands or .bands.gnu files Ex: 
[bands.out.gnu.txt](https://github.com/materialsautomated/materialsautomated.github.io/files/4430171/bands.out.gnu.txt)

**Output:** tab delimited spreadsheet, bands separated by columns, no repeated coordinate data Ex:
[bands.xlsx](https://github.com/materialsautomated/materialsautomated.github.io/files/4430173/bands.xlsx)

**Description:** QE (as accessed by MARCC) outputs band structure plots in a format which can be viewed as a static image via gnuplot. For those without an X11 viewer installed on the computer used to access MARCC, and those with a wish to do band selection/zooming, this is inconvenient.

It is possible to download and manually process the .bands file into a tab-delimited spreadsheet. The file as downloaded is a space-delimited list of bands, one after another oriented vertically. This is less convenient/universal than a tab-delimited spreadsheet. The long list is also difficult to visualize, and needlessly repeats the same list of coordinates with each list of band energies.

**Impact:** A tab-delimited spreadsheet with one column for coordinates followed by a series of columns of energies would be most easily used in spreadsheet-type applications. This is maybe more universal. It is definitely a time-saver if a spreadsheet is required for some reason. An alternative visualization method besides a static image viewer could also be useful.

**Comment by tmcqueen-materials** [comment]
Thanks for this request. Processing of DFT input/output files is extensively done by platforms such as the [Atomic Simulation Environment](https://wiki.fysik.dtu.dk/ase/). That said, it can be difficult to use the relevant components if not using ASE for the entire workflow. This is also a specific instantiation of a more general issue that crops up routinely: how to import files with different data structures in a usable way. So we will do both this DFT bands example, as well as an example Bruker RAW file importer, to demonstrate how to go about importing arbitrary data.

[DataTransform1Samples.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4651511/DataTransform1Samples.zip)
