### ISSUE TITLE
Simplistic generation of Laue diffraction pattern overlays using simulated crystal files

### ISSUE THREAD

**Issue by nng87** [materialsautomated/materialsautomated.github.io#9]
Inputs: 
-A simulated crystal file from QLaue(uses .xtl format) or other appropriate software
-Actual Laue diffraction pattern images

Output:
-A single image overlaying the simulated crystal image on the actual diffraction pattern

Description:
Laue diffraction comparisons seem to be done manually and appear to require some work to construct an appropriate overlaid figure if they are to be included in a submission to a journal. While working on Laue diffraction I found it quite frustrating to constantly have a second computer with QLaue open to glance at every time I modified the setup to figure out if the pattern looked right or if I needed to rotate the goniometer or any other similar modifications. 

With a program that can neatly output a single image overlaying the simulated diffraction pattern with an image taken directly by the Laue diffractometer, it may help simplify that process down to "Look at one overlaid image, figure out if it looks good, any changes needed are more obvious" since it can be done without having to look at multiple screens or even multiple images side by side, and it can help make aberrations such as crystal twinning more obvious.

A basic simulated image can be created by knowing how far your crystal is from the screen as well as what the pattern you are expecting should look like. The former is easily measured and the latter can be determined naively by the lattice parameters, space group, and atom positions of the material you are working with, assuming it is phase pure. Thus the inputs should be relatively simple to create.

Although the program would do nothing to help with the task of successfully aligning a crystal using Laue diffraction, the potential benefit would come from simplifying the comparison to simulated models such that it should be easier to know decisively if the alignment is successful. A secondary benefit, if the work is to be published in a journal, is that the overlaid figure can be used directly to show a successful proper alignment without the need to create a whole figure in some other software.

**Comment by tmcqueen-materials** [comment]
Thank you for this nice suggestion. If you could supply sample inputs and outputs, that would be helpful: you can include arbitrary file types by putting them in a zip archive first. 

I also suppose you’d want this tool to support common crystallography formats (eg cif), and perhaps even quantitatively model intensities given an incident white beam Xray profile and other salient diffractometer details?

**Comment by nng87** [comment]
[Sample Laue+CIF.zip](https://github.com/materialsautomated/materialsautomated.github.io/files/4505584/Sample.Laue%2BCIF.zip)
Apologies for the wait. Attached here is a .zip file containing a sample image of Nb3Br8 and HoFeO3 with associated .cif files sourced from ICSD.

The Nb3Br8 image was originally taken by Chris Pasco of the McQueen lab and the HoFeO3 image is from the following paper by Cao et. al. in 2011:
https://www.sciencedirect.com/science/article/pii/S0022024810009942?casa_token=RENV6JpzdGAAAAAA:K2XI3dQd-4H3HI6nv-mVfQ951cWOvSS8aYmQvu01Hsj6k8GzuDLNNFyXbzffWvCXjKZayr-Q5Q
